 - name: Upload App to Indus App Store
    id: upload-indus-app-store
    uses: yogeshpaliyal/upload-indus-appstore@<Latest Version>
    with:
      type: "UPLOAD_AAB"
      apiKey: ${{secrets.INDUS_API_KEY}}
      packageName: com.yogeshpaliyal.keypass
      aabFile: ./tempFiles/*.aab
      signingKeyBase64: ${{ secrets.SIGNING_KEY }}
      keystoreAlias: ${{ secrets.ALIAS }}
      keystorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      keyPassword: ${{ secrets.KEY_PASSWORD }}
